### PR TITLE
Lu playground

### PR DESCRIPTION
**Pull request by Luyanda-Mlangeni**
- updated send_bates function to now send communication_packet
- updated read_payload to now ntoh64 when needed
- changed range of octets to uint32 --> works better in combination with payload
- added TTL to communication_packet --> should be checked when collecting, we still have to decide on acceptable timeframe

### CODE REVIEW

**Comment by Stazer** [comment]
Looks good so far. Just one thing. Converting from host to network byte order is for our project pretty useless, since we all use the same architecture (x86). We should not bother, since it makes the implementation of the protocol right now more complicated than needed. Secondly, the translation is not implemented in the `buffer_reader` and `buffer_writer` classes in any way and therefor would make problems.

**Comment by Luyanda-Mlangeni** [comment]
Okay, I'll stop changing the byte order. What do you mean by translation?

**Comment by HClassen** [comment]
Looks good to me too. Like Justus said host to net byteorder is not implemented in the webots controller. After you  removed it, we can merge the pull request.

**Comment by Luyanda-Mlangeni** [comment]
Okay, changed it back to simply reading all uint8s. Going to merge now.

**Pull request merged**
