### PR TITLE
Lu playground

### PR DESCRIPTION
**Pull request by Luyanda-Mlangeni**
- Issue #36: test harness moved to test --> since the old harness directory no longer exists TravisCI can't cd to the harness directory. Merging should still be fine, if TravisCI is updated.

Screenshot 2020-06-23 at 19 06 40

- wrote mailbox and tcp tests

### CODE REVIEW

**Comment by Stazer** [comment]
I have created another branch `feature/test_project_structure`, which addresses the problem you have stated. Please rebase it onto yours by `git checkout luPlayground && git rebase feature/test_project_structure`. Afterwards, please push the changes to your branch, so that we can review your code.

**Comment by Luyanda-Mlangeni** [comment]
The test still seem to be failing. Do you know what the issue is / how I can resovle it?

**Comment by HClassen** [comment]
The CMake File is not the one in the master that is why the build is failing.

**Comment by Stazer** [comment]
There was an issue in your rebase. Fixed it. Please delete your local branch and check it out again. I merge this, since this is needed in master.

**Pull request merged**
